### ISSUE TITLE
`Player.prevCoordinates` uninitialized

### ISSUE THREAD

**Issue by nitzel** [dmalatesta/spaceterm#4]
If the `Player` collides on the first move, `prevCoordinates` is checked though it is not initialised yet.
Spawn the player at `0,0` and go to the `left` or to the `top` to cause this error.

You could deal with it by checking `prevCoordinates` against `None` in `Player.getDirection(self)`

**Comment by dmalatesta** [comment]
Fixed in fd7f41dd8205ba6c1920124ac7ce3fef5ce1b989
